/* BetriebsApp 1.0.16 – additive Erweiterungen */
(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ready(fn){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fn);else fn()}
function ensure(){db.storageMovements=db.storageMovements||[];db.grainMovements=db.grainMovements||[];(db.machines||[]).forEach(m=>m.photos=m.photos||[]);(db.fields||[]).forEach(f=>f.subAreas=f.subAreas||[])}

/* Lager: Änderungen als eigene Bewegung, ohne alte Arbeitsgänge anzufassen. */
window.quickStock=function(id,mode){const i=item(id);if(!i)return;openModal(mode==='sell'?'Verkaufen – '+i.name:'Bestand ändern – '+i.name,`<div class="note">Der bestehende Bestand und frühere Arbeitsgänge bleiben unverändert. Es wird nur eine neue Lagerbewegung gebucht.</div><div class="form3"><div><label>Datum</label><input id="qsDate" type="date" value="${today()}"></div><div><label>Menge (${esc(i.unit)})</label><input id="qsQty" type="number" min="0" step="0.1"></div><div><label>Grund</label><input id="qsReason" value="${mode==='sell'?'Verkauf':'Bestandskorrektur'}"></div></div><button class="primary" onclick="saveQuickStock('${id}','${mode}')">Buchen</button>`)};
window.saveQuickStock=function(id,mode){const q=num($('qsQty').value);if(!(q>0))return alert('Bitte eine Menge größer 0 eingeben.');const delta=mode==='add'?q:-q;if(sumStock(id)+delta<0&&!confirm('Der Bestand würde negativ. Trotzdem buchen?'))return;db.storageMovements.push({id:uid('mv'),itemId:id,date:$('qsDate').value||today(),delta,reason:$('qsReason').value.trim()||(mode==='sell'?'Verkauf':'Bestandskorrektur'),sourceType:mode==='sell'?'sale':'manual',sourceId:''});persist(mode==='sell'?'Lagerverkauf gebucht':'Lagerbestand geändert');closeModal()};
const oldStorageDetail=window.storageDetail;
window.storageDetail=function(id){oldStorageDetail(id);const d=document.querySelector('.modal.on .dialog');if(!d)return;const bar=document.createElement('div');bar.className='toolbar';bar.innerHTML=`<div><button class="primary" onclick="quickStock('${id}','add')">+ Hinzufügen</button> <button class="secondary" onclick="quickStock('${id}','remove')">− Wegnehmen</button> <button class="secondary" onclick="quickStock('${id}','sell')">Verkaufen</button></div><span class="small">ohne Änderung bestehender Arbeitsgänge</span>`;const h=[...d.querySelectorAll('h3')].find(x=>x.textContent==='Bewegungen');d.insertBefore(bar,h||d.firstChild)};

/* Getreide: separat hinzufügen, wegnehmen oder verkaufen. */
window.grainAdjust=function(id,mode){const g=(db.grainLots||[]).find(x=>x.id===id);if(!g)return;openModal(mode==='sell'?'Getreide verkaufen':'Getreidebestand ändern',`<div class="note"><b>${esc(g.crop)}</b> · aktuell ${fmt(g.currentKg,0)} kg<br>Die Änderung wird separat protokolliert und verändert keinen Arbeitsgang.</div><label>Menge kg</label><input id="gaQty" type="number" min="0" step="1"><label>Grund</label><input id="gaReason" value="${mode==='sell'?'Verkauf':'Bestandskorrektur'}"><br><button class="primary" onclick="saveGrainAdjust('${id}','${mode}')">Buchen</button>`)};
window.saveGrainAdjust=function(id,mode){const g=db.grainLots.find(x=>x.id===id),q=num($('gaQty').value);if(!g||!(q>0))return alert('Bitte eine Menge größer 0 eingeben.');const delta=mode==='add'?q:-q;if(num(g.currentKg)+delta<0&&!confirm('Der Bestand würde negativ. Trotzdem buchen?'))return;g.currentKg=num(g.currentKg)+delta;db.grainMovements.push({id:uid('gm'),lotId:id,date:today(),delta,reason:$('gaReason').value.trim()||(mode==='sell'?'Verkauf':'Bestandskorrektur'),type:mode==='sell'?'sale':'manual'});persist(mode==='sell'?'Getreide verkauft':'Getreidebestand geändert');closeModal()};
const oldGrain=window.grainLotDetail;
window.grainLotDetail=function(id){oldGrain(id);const d=document.querySelector('.modal.on .dialog');if(!d)return;const hist=(db.grainMovements||[]).filter(x=>x.lotId===id).sort((a,b)=>(b.date||'').localeCompare(a.date||''));const x=document.createElement('div');x.innerHTML=`<div class="toolbar"><div><button class="primary" onclick="grainAdjust('${id}','add')">+ Hinzufügen</button> <button class="secondary" onclick="grainAdjust('${id}','remove')">− Wegnehmen</button> <button class="secondary" onclick="grainAdjust('${id}','sell')">Verkaufen</button></div></div>${hist.length?'<h3>Manuelle Bewegungen</h3>'+hist.map(h=>`<div class="note" style="margin:5px 0">${h.date} · ${h.delta>0?'+':''}${fmt(h.delta,0)} kg · ${esc(h.reason)}</div>`).join(''):''}`;const h=[...d.querySelectorAll('h3')][0];d.insertBefore(x,h||d.firstChild)};

/* Teilflächen: frei innerhalb der gespeicherten Feldgrenze zeichnen. */
let splitMap=null,drawLayer=null,splitFieldId=null;
function loadScript(src){return new Promise((res,rej)=>{if([...document.scripts].some(s=>s.src===src))return res();const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
window.openSubAreas=async function(id){const f=field(id);if(!f?.geometry)return alert('Für dieses Feld ist keine Feldgrenze gespeichert. Bitte zuerst die Feldgrenze über die Karte/INVEKOS übernehmen.');splitFieldId=id;try{await loadScript('https://cdn.jsdelivr.net/npm/@turf/turf@7/turf.min.js')}catch(e){return alert('Kartenfunktion konnte nicht geladen werden. Bitte Internetverbindung prüfen.')}openModal('Teilflächen – '+f.name,`<div class="note">Zeichne die gewünschte Teilfläche direkt innerhalb des Feldes. Danach Kultur und Jahr vergeben. So kannst du z. B. 1 ha Weizen und den Rest Roggen planen.</div><div id="splitMap" style="height:52vh;min-height:380px;margin:10px 0;border:1px solid #d9e2db;border-radius:12px"></div><div class="form3"><div><label>Name</label><input id="saName" placeholder="z. B. Straßacker Weizen"></div><div><label>Kultur</label><input id="saCrop" placeholder="z. B. Weizen"></div><div><label>Jahr</label><input id="saYear" type="number" value="${rotationYear()}"></div></div><div id="saArea" class="note">Noch keine Teilfläche gezeichnet.</div><button class="primary" onclick="saveSubArea()">Gezeichnete Teilfläche speichern</button><h3>Gespeicherte Teilflächen</h3><div id="saList"></div>`);setTimeout(()=>initSplitMap(f),80)};
function initSplitMap(f){splitMap=L.map('splitMap');L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'}).addTo(splitMap);const base=L.geoJSON({type:'Feature',geometry:f.geometry},{style:{color:'#315f3a',weight:4,fillOpacity:.08}}).addTo(splitMap);splitMap.fitBounds(base.getBounds(),{padding:[20,20]});drawLayer=L.featureGroup().addTo(splitMap);let drawing=false,pts=[];const hint=L.control({position:'topright'});hint.onAdd=()=>{const d=L.DomUtil.create('div');d.style='background:white;padding:8px;border-radius:8px;box-shadow:0 1px 5px #999';d.innerHTML='<b>Klicken:</b> Eckpunkte setzen<br><b>Doppelklick:</b> Fläche abschließen';return d};hint.addTo(splitMap);splitMap.doubleClickZoom.disable();splitMap.on('click',e=>{if(!drawing){drawing=true;pts=[];drawLayer.clearLayers()}pts.push(e.latlng);L.polyline(pts,{weight:3}).addTo(drawLayer)});splitMap.on('dblclick',e=>{L.DomEvent.stop(e);if(pts.length<3)return;drawLayer.clearLayers();const poly=L.polygon(pts,{weight:3,fillOpacity:.25}).addTo(drawLayer);poly._saCoords=pts.map(p=>[p.lng,p.lat]);drawing=false;const ring=[...poly._saCoords,poly._saCoords[0]],a=turf.area(turf.polygon([ring]))/10000;$('saArea').innerHTML=`Gezeichnet: <b>${fmt(a,2)} ha</b>`;drawLayer._activePoly=poly});renderSubAreaList(f)}
function renderSubAreaList(f){const e=$('saList');if(!e)return;e.innerHTML=(f.subAreas||[]).map(s=>`<div class="note" style="margin:5px 0"><b>${esc(s.name||s.crop)}</b> · ${esc(s.crop)} · ${fmt(s.area,2)} ha · ${s.year} <button class="secondary" style="float:right;padding:3px 7px" onclick="deleteSubArea('${f.id}','${s.id}')">Löschen</button></div>`).join('')||'<div class="small">Noch keine Teilflächen.</div>'}
window.saveSubArea=function(){const f=field(splitFieldId),p=drawLayer?._activePoly;if(!f||!p?._saCoords)return alert('Bitte zuerst eine Teilfläche auf der Karte zeichnen.');const ring=[...p._saCoords,p._saCoords[0]],feature=turf.polygon([ring]),area=turf.area(feature)/10000,center=turf.pointOnFeature(feature);if(!turf.booleanPointInPolygon(center,{type:'Feature',geometry:f.geometry}))return alert('Die gezeichnete Teilfläche liegt nicht innerhalb des Feldes.');f.subAreas=f.subAreas||[];f.subAreas.push({id:uid('sa'),name:$('saName').value.trim()||$('saCrop').value.trim()||'Teilfläche',crop:$('saCrop').value.trim(),year:num($('saYear').value)||rotationYear(),area,geometry:feature.geometry});persist('Teilfläche gespeichert');renderSubAreaList(f);drawLayer.clearLayers();drawLayer._activePoly=null;$('saArea').textContent='Teilfläche gespeichert. Du kannst die nächste zeichnen.'};
window.deleteSubArea=function(fid,sid){const f=field(fid);if(!f)return;f.subAreas=(f.subAreas||[]).filter(x=>x.id!==sid);persist('Teilfläche gelöscht');renderSubAreaList(f)};
const oldFieldDetail=window.fieldDetail;
window.fieldDetail=function(id){oldFieldDetail(id);const f=field(id),d=document.querySelector('.modal.on .dialog');if(!d||!f)return;const b=document.createElement('button');b.className='secondary';b.style.marginLeft='5px';b.textContent='Teilflächen planen';b.onclick=()=>openSubAreas(id);const edit=[...d.querySelectorAll('button')].find(x=>x.textContent.includes('Feld bearbeiten'));if(edit)edit.after(b);else d.querySelector('.modalhead')?.appendChild(b)};

/* Maschinenbilder / Unterlagen */
const oldMachine=window.machineDetail;
window.machineDetail=function(id){oldMachine(id);const m=db.machines.find(x=>x.id===id),d=document.querySelector('.modal.on .dialog');if(!m||!d)return;m.photos=m.photos||[];const sec=document.createElement('div');sec.innerHTML=`<h3>Bilder & Unterlagen</h3><div class="note">Hier kannst du z. B. ein Foto der Abdrehprobe oder einer Seite aus der Betriebsanleitung speichern.</div><input id="machinePhoto" type="file" accept="image/*" onchange="saveMachinePhoto('${id}',this)"><div class="grid3" style="margin-top:8px">${m.photos.map((p,i)=>`<div class="card"><img class="pic" src="${p.data}"><div class="small">${esc(p.name||'Bild')}</div><button class="secondary" onclick="deleteMachinePhoto('${id}',${i})">Löschen</button></div>`).join('')}</div>`;const hist=[...d.querySelectorAll('h3')].find(x=>x.textContent==='Historie');d.insertBefore(sec,hist||null)};
window.saveMachinePhoto=function(id,input){const f=input.files?.[0];if(!f)return;if(f.size>4*1024*1024)return alert('Das Bild ist zu groß. Bitte maximal 4 MB verwenden.');const r=new FileReader();r.onload=()=>{const m=db.machines.find(x=>x.id===id);m.photos=m.photos||[];m.photos.push({name:f.name,date:today(),data:r.result});persist('Maschinenbild gespeichert');closeModal();setTimeout(()=>machineDetail(id),50)};r.readAsDataURL(f)};
window.deleteMachinePhoto=function(id,i){const m=db.machines.find(x=>x.id===id);if(!m)return;m.photos.splice(i,1);persist('Maschinenbild gelöscht');closeModal();setTimeout(()=>machineDetail(id),50)};

/* Sync-Anzeige oben wird zum direkten Sync-Knopf. */
function applyVersionUi(){const v=document.querySelector('.desktopHint');if(v)v.textContent='Version 1.0.16';const s=$('syncIndicator');if(s){s.style.cursor='pointer';s.title='Klicken zum Synchronisieren';s.onclick=()=>manualSync()}}
ready(()=>{ensure();applyVersionUi();const oldRender=window.renderAll;window.renderAll=function(){ensure();oldRender();applyVersionUi()};renderAll()});
})();