/* BetriebsApp 1.0.16 – additive Erweiterungen */
(()=>{
'use strict';
if(window.__BETRIEBSAPP_1016_LOADED__) return;
window.__BETRIEBSAPP_1016_LOADED__=true;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ready(fn){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fn);else fn()}
function ensure(){db.storageMovements=db.storageMovements||[];db.grainMovements=db.grainMovements||[];db.seedMovements=db.seedMovements||[];(db.machines||[]).forEach(m=>m.photos=m.photos||[]);(db.fields||[]).forEach(f=>f.subAreas=f.subAreas||[]);db.settings=db.settings||{};db.settings.baleWeights=db.settings.baleWeights||{};const sw=Number(db.settings.baleWeights['Silage Ballen'])||Number(db.settings.baleWeights['Silage'])||0;if(sw>0)(db.storageItems||[]).filter(i=>i.unit==='Ballen'&&/silo|silage/i.test(i.name||'')).forEach(i=>{if(!(Number(db.settings.baleWeights[i.name])>0))db.settings.baleWeights[i.name]=sw})}
function modalBody(){return $('modalBody')}

/* Normale Lagerartikel: Futter, Kraftfutter und Sonstige */
window.quickStock=function(id,mode){const i=item(id);if(!i)return;openModal(mode==='sell'?'Verkaufen – '+i.name:'Bestand ändern – '+i.name,`<div class="note">Der bestehende Bestand und frühere Arbeitsgänge bleiben unverändert. Es wird nur eine neue Lagerbewegung gebucht.</div><div class="form3"><div><label>Datum</label><input id="qsDate" type="date" value="${today()}"></div><div><label>Menge (${esc(i.unit)})</label><input id="qsQty" type="number" min="0" step="0.1"></div><div><label>Grund</label><input id="qsReason" value="${mode==='sell'?'Verkauf':'Bestandskorrektur'}"></div></div><button class="primary" onclick="saveQuickStock('${id}','${mode}')">Buchen</button>`)};
window.saveQuickStock=function(id,mode){const q=num($('qsQty').value);if(!(q>0))return alert('Bitte eine Menge größer 0 eingeben.');const delta=mode==='add'?q:-q;if(sumStock(id)+delta<0&&!confirm('Der Bestand würde negativ. Trotzdem buchen?'))return;db.storageMovements.push({id:uid('mv'),itemId:id,date:$('qsDate').value||today(),delta,reason:$('qsReason').value.trim()||(mode==='sell'?'Verkauf':'Bestandskorrektur'),sourceType:mode==='sell'?'sale':'manual',sourceId:''});persist(mode==='sell'?'Lagerverkauf gebucht':'Lagerbestand geändert');closeModal()};
const oldStorageDetail=window.storageDetail;window.storageDetail=function(id){oldStorageDetail(id);const d=modalBody();if(!d)return;const bar=document.createElement('div');bar.className='toolbar ext-stock-toolbar';bar.innerHTML=`<div><button class="primary" onclick="quickStock('${id}','add')">+ Hinzufügen</button> <button class="secondary" onclick="quickStock('${id}','remove')">− Wegnehmen</button> <button class="secondary" onclick="quickStock('${id}','sell')">Verkaufen</button></div><span class="small">ohne Änderung bestehender Arbeitsgänge</span>`;d.prepend(bar)};

/* Getreide */
window.grainAdjust=function(id,mode){const g=(db.grainLots||[]).find(x=>x.id===id);if(!g)return;openModal(mode==='sell'?'Getreide verkaufen':'Getreidebestand ändern',`<div class="note"><b>${esc(g.crop)}</b> · aktuell ${fmt(g.currentKg,0)} kg<br>Die Änderung wird separat protokolliert und verändert keinen Arbeitsgang.</div><label>Menge kg</label><input id="gaQty" type="number" min="0" step="1"><label>Grund</label><input id="gaReason" value="${mode==='sell'?'Verkauf':'Bestandskorrektur'}"><br><button class="primary" onclick="saveGrainAdjust('${id}','${mode}')">Buchen</button>`)};
window.saveGrainAdjust=function(id,mode){const g=db.grainLots.find(x=>x.id===id),q=num($('gaQty').value);if(!g||!(q>0))return alert('Bitte eine Menge größer 0 eingeben.');const delta=mode==='add'?q:-q;if(num(g.currentKg)+delta<0&&!confirm('Der Bestand würde negativ. Trotzdem buchen?'))return;g.currentKg=num(g.currentKg)+delta;db.grainMovements.push({id:uid('gm'),lotId:id,date:today(),delta,reason:$('gaReason').value.trim()||(mode==='sell'?'Verkauf':'Bestandskorrektur'),type:mode==='sell'?'sale':'manual'});persist(mode==='sell'?'Getreide verkauft':'Getreidebestand geändert');closeModal()};
const oldGrain=window.grainLotDetail;window.grainLotDetail=function(id){oldGrain(id);const d=modalBody();if(!d)return;const hist=(db.grainMovements||[]).filter(x=>x.lotId===id).sort((a,b)=>(b.date||'').localeCompare(a.date||''));const x=document.createElement('div');x.innerHTML=`<div class="toolbar"><div><button class="primary" onclick="grainAdjust('${id}','add')">+ Hinzufügen</button> <button class="secondary" onclick="grainAdjust('${id}','remove')">− Wegnehmen</button> <button class="secondary" onclick="grainAdjust('${id}','sell')">Verkaufen</button></div></div>${hist.length?'<h3>Manuelle Bewegungen</h3>'+hist.map(h=>`<div class="note" style="margin:5px 0">${h.date} · ${h.delta>0?'+':''}${fmt(h.delta,0)} kg · ${esc(h.reason)}</div>`).join(''):''}`;d.prepend(x)};

/* Saatgut: gleiche Buchungsmöglichkeiten wie Getreide */
window.seedAdjust=function(id,mode){const s=(db.seedLots||[]).find(x=>x.id===id);if(!s)return;openModal(mode==='sell'?'Saatgut verkaufen':'Saatgutbestand ändern',`<div class="note"><b>${esc(s.crop)} ${esc(s.variety||'')}</b> · aktuell ${fmt(s.currentKg,0)} kg<br>Automatische Abbuchungen aus Säarbeitsgängen bleiben unverändert.</div><label>Menge kg</label><input id="saQty" type="number" min="0" step="0.1"><label>Grund</label><input id="saReason" value="${mode==='sell'?'Verkauf':'Bestandskorrektur'}"><br><button class="primary" onclick="saveSeedAdjust('${id}','${mode}')">Buchen</button>`)};
window.saveSeedAdjust=function(id,mode){const s=(db.seedLots||[]).find(x=>x.id===id),q=num($('saQty').value);if(!s||!(q>0))return alert('Bitte eine Menge größer 0 eingeben.');const delta=mode==='add'?q:-q;if(num(s.currentKg)+delta<0&&!confirm('Der Bestand würde negativ. Trotzdem buchen?'))return;s.currentKg=num(s.currentKg)+delta;db.seedMovements.push({id:uid('sm'),lotId:id,date:today(),delta,reason:$('saReason').value.trim()||(mode==='sell'?'Verkauf':'Bestandskorrektur'),sourceType:mode==='sell'?'sale':'manual',sourceWorkId:''});persist(mode==='sell'?'Saatgut verkauft':'Saatgutbestand geändert');closeModal()};
const oldSeed=window.seedLotDetail;window.seedLotDetail=function(id){oldSeed(id);const d=modalBody();if(!d)return;const bar=document.createElement('div');bar.className='toolbar';bar.innerHTML=`<div><button class="primary" onclick="seedAdjust('${id}','add')">+ Hinzufügen</button> <button class="secondary" onclick="seedAdjust('${id}','remove')">− Wegnehmen</button> <button class="secondary" onclick="seedAdjust('${id}','sell')">Verkaufen</button></div>`;d.prepend(bar)};

/* Fahrsilo-Umrechnung unabhängig von der Artikel-ID nach Einheit/Name */
const baseBaleWeight=window.baleWeightForItem;
window.baleWeightForItem=function(i){const v=baseBaleWeight(i);if(v>0)return v;if(i&&i.unit==='Ballen'&&/silo|silage/i.test(i.name||'')){const w=db.settings?.baleWeights||{};return Number(w['Silage Ballen'])||Number(w['Silage'])||0}return 0};
const baseRenderStorage=window.renderStorage;window.renderStorage=function(){baseRenderStorage();const feeds=(db.storageItems||[]).filter(i=>i.category==='Futter');const rows=$('feed')?.querySelectorAll('tr.rowclick')||[];rows.forEach((r,idx)=>{const i=feeds[idx];if(!i)return;const cells=r.querySelectorAll('td');if(cells.length<4)return;const u=String(i.unit||'').toLowerCase();if((u.includes('m³')||u.includes('m3'))&&/silo|silage/i.test(i.name||'')){const factor=Number(db.settings?.siloTonnesPerM3)||0;cells[3].textContent=factor>0?'≈ '+fmt(sumStock(i.id)*factor)+' t ('+fmt(factor,2)+' t/m³)':'Umrechnung fehlt'}})};

/* Teilflächen */
let splitMap=null,drawLayer=null,splitFieldId=null;
function loadScript(src){return new Promise((res,rej)=>{if([...document.scripts].some(s=>s.src===src))return res();const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
window.openSubAreas=async function(id){const f=field(id);if(!f?.geometry)return alert('Für dieses Feld ist keine Feldgrenze gespeichert. Bitte zuerst die Feldgrenze über die Karte/INVEKOS übernehmen.');splitFieldId=id;try{await loadScript('https://cdn.jsdelivr.net/npm/@turf/turf@7/turf.min.js')}catch(e){return alert('Kartenfunktion konnte nicht geladen werden. Bitte Internetverbindung prüfen.')}openModal('Teilflächen – '+f.name,`<div class="note">Gespeicherte Teilflächen werden auf der Karte angezeigt. Du kannst weitere Teilflächen zeichnen und sie danach in der Fruchtfolgeplanung einzeln auswählen.</div><div id="splitMap" style="height:52vh;min-height:380px;margin:10px 0;border:1px solid #d9e2db;border-radius:12px"></div><div class="form3"><div><label>Name</label><input id="subName" placeholder="z. B. Straßacker Weizen"></div><div><label>Kultur</label><input id="subCrop" placeholder="z. B. Weizen"></div><div><label>Jahr</label><input id="subYear" type="number" value="${rotationYear()}"></div></div><div id="subAreaInfo" class="note">Noch keine neue Teilfläche gezeichnet.</div><button class="primary" onclick="saveSubArea()">Gezeichnete Teilfläche speichern</button><h3>Gespeicherte Teilflächen</h3><div id="saList"></div>`);setTimeout(()=>initSplitMap(f),80)};
function initSplitMap(f){splitMap=L.map('splitMap');L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{y}/{x}.png'.replace('{y}/{x}','{x}/{y}'),{maxZoom:20,attribution:'© OpenStreetMap'}).addTo(splitMap);const base=L.geoJSON({type:'Feature',geometry:f.geometry},{style:{color:'#315f3a',weight:4,fillOpacity:.05}}).addTo(splitMap);splitMap.fitBounds(base.getBounds(),{padding:[20,20]});drawLayer=L.featureGroup().addTo(splitMap);(f.subAreas||[]).forEach(s=>{if(!s.geometry)return;L.geoJSON({type:'Feature',geometry:s.geometry},{style:{weight:3,fillOpacity:.28}}).bindTooltip(`${esc(s.name||s.crop)} · ${fmt(s.area,2)} ha`,{permanent:false}).addTo(drawLayer)});let drawing=false,pts=[];splitMap.doubleClickZoom.disable();splitMap.on('click',e=>{if(!drawing){drawing=true;pts=[]}pts.push(e.latlng);L.polyline(pts,{weight:3}).addTo(drawLayer)});splitMap.on('dblclick',e=>{L.DomEvent.stop(e);if(pts.length<3)return;const poly=L.polygon(pts,{weight:3,fillOpacity:.25}).addTo(drawLayer);poly._saCoords=pts.map(p=>[p.lng,p.lat]);drawing=false;pts=[];const ring=[...poly._saCoords,poly._saCoords[0]],a=turf.area(turf.polygon([ring]))/10000;$('subAreaInfo').innerHTML=`Gezeichnet: <b>${fmt(a,2)} ha</b>`;drawLayer._activePoly=poly});renderSubAreaList(f)}
function renderSubAreaList(f){const e=$('saList');if(!e)return;e.innerHTML=(f.subAreas||[]).map(s=>`<div class="note" style="margin:5px 0"><b>${esc(s.name||s.crop)}</b> · ${esc(s.crop||'–')} · ${fmt(s.area,2)} ha · ${s.year||'–'} <button class="secondary" style="float:right;padding:3px 7px" onclick="deleteSubArea('${f.id}','${s.id}')">Löschen</button></div>`).join('')||'<div class="small">Noch keine Teilflächen.</div>'}
window.saveSubArea=function(){const f=field(splitFieldId),p=drawLayer?._activePoly;if(!f||!p?._saCoords)return alert('Bitte zuerst eine Teilfläche auf der Karte zeichnen.');const ring=[...p._saCoords,p._saCoords[0]],feature=turf.polygon([ring]),area=turf.area(feature)/10000,center=turf.pointOnFeature(feature);if(!turf.booleanPointInPolygon(center,{type:'Feature',geometry:f.geometry}))return alert('Die gezeichnete Teilfläche liegt nicht innerhalb des Feldes.');f.subAreas=f.subAreas||[];f.subAreas.push({id:uid('sa'),name:$('subName').value.trim()||$('subCrop').value.trim()||'Teilfläche',crop:$('subCrop').value.trim(),year:num($('subYear').value)||rotationYear(),area,geometry:feature.geometry});persist('Teilfläche gespeichert');closeModal();setTimeout(()=>openSubAreas(f.id),80)};
window.deleteSubArea=function(fid,sid){const f=field(fid);if(!f)return;if(!confirm('Teilfläche wirklich löschen?'))return;f.subAreas=(f.subAreas||[]).filter(x=>x.id!==sid);db.rotationPlans=(db.rotationPlans||[]).filter(p=>p.subAreaId!==sid);persist('Teilfläche gelöscht');closeModal();setTimeout(()=>openSubAreas(fid),80)};
const oldFieldDetail=window.fieldDetail;window.fieldDetail=function(id){oldFieldDetail(id);const f=field(id),d=modalBody();if(!d||!f)return;const b=document.createElement('button');b.className='secondary';b.style.marginLeft='5px';b.textContent='Teilflächen planen';b.onclick=()=>openSubAreas(id);const edit=[...d.querySelectorAll('button')].find(x=>x.textContent.includes('Feld bearbeiten'));if(edit)edit.after(b);else d.prepend(b)};

/* Teilflächen zusätzlich in der Fruchtfolgeplanung */
const oldRotationPlanner=window.rotationPlanner;window.rotationPlanner=function(preselectId=''){oldRotationPlanner(preselectId);const list=document.querySelector('#modalBody .checklist');if(!list)return;const y=rotationYear();const subs=(db.fields||[]).flatMap(f=>(f.subAreas||[]).map(s=>({f,s}))).filter(x=>Number(x.s.year||y)===Number(y));if(!subs.length)return;const title=document.createElement('div');title.innerHTML='<label>Teilflächen auswählen</label><div class="small">Teilflächen werden getrennt vom ganzen Feld geplant.</div>';list.after(title);const box=document.createElement('div');box.className='checklist';box.innerHTML=subs.map(({f,s})=>{const old=(db.rotationPlans||[]).find(p=>p.subAreaId===s.id&&Number(p.year)===y);return `<label><input type="checkbox" class="rpSub" data-field="${f.id}" value="${s.id}" onchange="calcRotation()"><b>${esc(f.name)} – ${esc(s.name||s.crop)}</b> · ${fmt(s.area,2)} ha${old?` · geplant: <b>${esc(old.crop)}</b>`:''}</label>`}).join('');title.after(box);const btn=[...document.querySelectorAll('#modalBody button')].find(b=>b.textContent.includes('Plan speichern'));if(btn)btn.setAttribute('onclick','saveRotation1016()');calcRotation()};
const oldCalcRotation=window.calcRotation;window.calcRotation=function(){oldCalcRotation();const subs=[...document.querySelectorAll('.rpSub:checked')];if(!subs.length)return;const full=[...document.querySelectorAll('.rpField:checked')].reduce((a,x)=>a+num(field(x.value)?.area),0);const sa=subs.reduce((a,x)=>{const f=field(x.dataset.field),s=(f?.subAreas||[]).find(z=>z.id===x.value);return a+num(s?.area)},0);const a=full+sa,sel=$('rpCrop'),crop=sel?.value==='__custom__'?($('rpCustom')?.value.trim()||''):(sel?.value||''),rate=num($('rpRate')?.value),need=a*rate,have=seedStockForCrop(crop);if($('rpSelected'))$('rpSelected').textContent=fmt(a)+' ha';if($('rpInfo')&&crop)$('rpInfo').innerHTML=`Saatgutbedarf: <b>${fmt(need,0)} kg</b> · Bestand: <b>${fmt(have,0)} kg</b> · <span class="${have>=need?'green':'red'}"><b>${have>=need?'reicht':'zu wenig'}</b></span>`};
window.saveRotation1016=function(){const y=rotationYear(),sel=$('rpCrop'),crop=sel?.value==='__custom__'?($('rpCustom')?.value.trim()||''):(sel?.value||''),rate=Number($('rpRate')?.value),ids=[...document.querySelectorAll('.rpField:checked')].map(x=>x.value),subs=[...document.querySelectorAll('.rpSub:checked')];if(!ids.length&&!subs.length)return alert('Bitte mindestens ein Feld oder eine Teilfläche auswählen.');if(!crop)return alert('Bitte eine Kultur auswählen oder eingeben.');if(!Number.isFinite(rate)||rate<0)return alert('Saatmenge prüfen.');db.rotationPlans=db.rotationPlans||[];ids.forEach(id=>{const f=field(id);if(!f||isPermanentGrassland(f))return;db.rotationPlans=db.rotationPlans.filter(p=>!(p.fieldId===id&&!p.subAreaId&&Number(p.year)===y));db.rotationPlans.push({id:uid('rp'),year:y,fieldId:id,crop,area:num(f.area),seedRate:rate,status:'geplant'})});subs.forEach(x=>{const f=field(x.dataset.field),s=(f?.subAreas||[]).find(z=>z.id===x.value);if(!f||!s)return;db.rotationPlans=db.rotationPlans.filter(p=>!(p.subAreaId===s.id&&Number(p.year)===y));db.rotationPlans.push({id:uid('rp'),year:y,fieldId:f.id,subAreaId:s.id,subAreaName:s.name||s.crop,crop,area:num(s.area),seedRate:rate,status:'geplant'})});persist(`Fruchtfolge ${y} geplant`);closeModal()};

/* Maschinenbilder / Unterlagen – vollständig getrennt von Lager und Arbeitsgängen. */
const oldMachine=window.machineDetail;window.machineDetail=function(id){oldMachine(id);const m=db.machines.find(x=>x.id===id),d=modalBody();if(!m||!d)return;m.photos=m.photos||[];const sec=document.createElement('div');sec.innerHTML=`<h3>Bilder & Unterlagen</h3><div class="note">Hier kannst du z. B. ein Foto der Abdrehprobe oder einer Seite aus der Betriebsanleitung speichern.</div><input id="machinePhoto" type="file" accept="image/*" onchange="saveMachinePhoto('${id}',this)"><div class="grid3" style="margin-top:8px">${m.photos.map((p,i)=>`<div class="card"><img class="pic" src="${p.data}"><div class="small">${esc(p.name||'Bild')}</div><button class="secondary" onclick="deleteMachinePhoto('${id}',${i})">Löschen</button></div>`).join('')}</div>`;const hist=[...d.querySelectorAll('h3')].find(x=>x.textContent==='Historie');d.insertBefore(sec,hist||null)};
window.saveMachinePhoto=function(id,input){const f=input.files?.[0];if(!f)return;if(f.size>4*1024*1024)return alert('Das Bild ist zu groß. Bitte maximal 4 MB verwenden.');const r=new FileReader();r.onload=()=>{const m=db.machines.find(x=>x.id===id);m.photos=m.photos||[];m.photos.push({name:f.name,date:today(),data:r.result});persist('Maschinenbild gespeichert');closeModal();setTimeout(()=>machineDetail(id),50)};r.readAsDataURL(f)};window.deleteMachinePhoto=function(id,i){const m=db.machines.find(x=>x.id===id);if(!m)return;m.photos.splice(i,1);persist('Maschinenbild gelöscht');closeModal();setTimeout(()=>machineDetail(id),50)};window.deleteMachine=function(id){const m=(db.machines||[]).find(x=>x.id===id);if(!m)return;if(!confirm(`Maschine „${m.name||'Maschine'}“ wirklich löschen?`))return;db.machines=db.machines.filter(x=>x.id!==id);db.calendarEvents=(db.calendarEvents||[]).filter(e=>e.sourceId!=='machine:'+id);persist('Maschine gelöscht');closeModal()};

function applyVersionUi(){const v=document.querySelector('.desktopHint');if(v)v.textContent='Version 1.0.16';const s=$('syncIndicator');if(s){s.style.cursor='pointer';s.title='Klicken zum Synchronisieren';s.onclick=()=>manualSync()}}
ready(()=>{ensure();applyVersionUi();const oldRender=window.renderAll;window.renderAll=function(){ensure();oldRender();applyVersionUi()};renderAll()});
})();